/* ================================================================
   EASY CONTENT SETTINGS
   Edit only the text between quotes. Keep commas and brackets intact.
   Full instructions: HOW-TO-UPDATE.md
   ================================================================ */

window.PORTFOLIO_CONTENT = {
  contact: {
    email: "adinrajpoot@gmail.com",
    linkedin: "https://www.linkedin.com/in/adnan-afzal-growth/",

    // Paste your Google Calendar appointment-schedule link below.
    // Leave empty ("") until it is ready; the site will show "Coming soon".
    bookingUrl: "",

    // Optional: paste a permanent Google Meet link here.
    // Calendar appointments can also create a unique Meet link automatically.
    googleMeetUrl: "",

    responseTime: "Usually replies within 24–48 hours"
  },

  availability: [
    "Monday · 6–9 PM PKT",
    "Wednesday · 6–9 PM PKT",
    "Saturday · 12–5 PM PKT"
  ],

  consultationTypes: [
    {
      title: "ASO Consultation",
      duration: "45 minutes",
      description: "Store audit covering keywords, metadata, creative conversion, competitors, and an actionable testing roadmap.",
      topics: ["Keyword strategy", "Store conversion", "Creative testing"]
    },
    {
      title: "UAC & Paid Growth",
      duration: "60 minutes",
      description: "Campaign diagnosis for Google UAC, Meta, or TikTok with practical actions for CPI, ROAS, and scaling.",
      topics: ["Campaign structure", "Creative signals", "Scaling plan"]
    },
    {
      title: "Monetization Review",
      duration: "45 minutes",
      description: "A focused review of ad placements, IAP structure, live ops, and the metrics affecting revenue quality.",
      topics: ["ARPDAU", "Ad mediation", "IAP & live ops"]
    },
    {
      title: "Overall Growth Audit",
      duration: "75 minutes",
      description: "A full-funnel review connecting acquisition, ASO, retention, analytics, and monetization into one roadmap.",
      topics: ["Full funnel", "Priority roadmap", "Growth systems"]
    }
  ],

  faqs: [
    {
      question: "Who are consultations best suited for?",
      answer: "Mobile app and game founders, marketing teams, product managers, and studios that need a clear diagnosis or practical growth roadmap."
    },
    {
      question: "What should I share before the call?",
      answer: "Your store links, current goal, key performance numbers, target markets, and the main problem you want to solve. Sensitive access is not required for an initial consultation."
    },
    {
      question: "Will I receive recommendations after the session?",
      answer: "Yes. The session focuses on prioritized actions, testing ideas, and the next decisions your team should make. Scope for a written audit can be agreed separately."
    },
    {
      question: "Can you support implementation after the consultation?",
      answer: "Yes, depending on availability and fit. Ongoing advisory, audits, and execution support can be discussed after the initial session."
    },
    {
      question: "How are calls scheduled?",
      answer: "Choose an available time through Google Calendar. The booking confirmation can include a Google Meet link automatically."
    }
  ],

  /* ADD A NEW BLOG: copy one complete { ... } block and change its text.
     Use a unique id with lowercase words and hyphens. */
  blogs: [
    {
      id: "aso-ua",
      category: "Strategy",
      readTime: "7 min read",
      date: "June 12, 2026",
      title: "Why ASO and paid acquisition should share one feedback loop",
      summary: "The most expensive growth leak often happens between the ad click and the store page.",
      content: `
        <p>Teams often manage paid acquisition and app store optimization as separate workstreams. One team buys attention; another improves the listing. That separation is tidy on an org chart and expensive in the market.</p>
        <h3>The hidden leak</h3>
        <p>An ad does not finish its job at the click. It creates an expectation that the store page must continue. When the message, visual language, or audience promise changes between those surfaces, conversion falls—and paid media gets blamed for a store-level problem.</p>
        <blockquote>Treat the ad and the store page as two consecutive frames of the same story.</blockquote>
        <h3>A useful operating rhythm</h3>
        <ol><li>Group creative concepts by the user promise they make.</li><li>Track store conversion for the traffic generated by each promise.</li><li>Move winning language and visual cues into store experiments.</li><li>Feed store learnings back into the next paid creative sprint.</li></ol>
        <p>This loop does more than improve conversion. Better post-click performance gives acquisition algorithms cleaner signals, protects CPI, and can strengthen organic visibility at the same time.</p>`
    },
    {
      id: "scale",
      category: "User Acquisition",
      readTime: "5 min read",
      date: "May 28, 2026",
      title: "Scale spend without losing signal quality",
      summary: "A practical framework for controlled campaign expansion without sacrificing cohort value.",
      content: `
        <p>Scaling is not simply increasing budget. It changes the auction, broadens the audience, alters the creative mix, and can expose weak retention that looked harmless at lower volume.</p>
        <h3>Scale in controlled layers</h3>
        <p>Start with one variable at a time: geography, budget, creative, or audience. Set a learning window before judging the change, and define the metric that can stop the experiment.</p>
        <h3>Watch the whole cohort</h3>
        <p>CPI is an entry price, not a verdict. Read it alongside activation, early retention, payer conversion, and revenue quality. If install cost improves while downstream value collapses, the campaign found cheaper—not better—users.</p>`
    },
    {
      id: "metrics",
      category: "Analytics",
      readTime: "6 min read",
      date: "May 10, 2026",
      title: "The metrics that make growth decisions clearer",
      summary: "Move beyond crowded dashboards toward measurement that supports real decisions.",
      content: `
        <p>A dashboard can contain every number and still answer no question. Useful measurement begins with the decision a team needs to make.</p>
        <h3>Build a decision stack</h3>
        <p>Use three levels: an outcome metric such as ROAS or LTV; diagnostic metrics such as retention, conversion, and ARPDAU; and input metrics such as spend, creative volume, and experiment velocity.</p>
        <h3>Prefer cohorts to averages</h3>
        <p>Blended averages hide change. Compare cohorts by acquisition date, channel, creative promise, and market. A smaller clean cohort often teaches more than a large blended total.</p>`
    }
  ]
};
 
